name: Docker image
on:
  push:
    branches:
      - main
jobs:
  Publish_Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker tag action
      uses: moleszek/docker_tag@1.3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: "moleszek/terraform"
        tag_latest: "false"
    - name: Update Docker README
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: moleszek/terraform
        README_FILEPATH: README.md