name: Publish docker image
on:
  push:
    branches:
      - auto_update
  #release:
  #  types: 
  #    - published
jobs:
  Test_Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: get docker_tag repository
      uses: actions/checkout@v2
      with:
        repository: solairen/docker_tag
        ref: new_functionality
        token: ${{ secrets.token }}
        path: .github/actions/solairen/docker_tag
    - name: test
      run: "ls -la"
    - name: test docker image
      uses: ./.github/actions/solairen/docker_tag
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: "moleszek/terraform"
        tag_latest: "false"
        push: "false"
        path: ${pwd}
  #Push_Image:
  #  needs: Test_Image
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: get docker_tag repository
  #    uses: actions/checkout@v2
  #    with:
  #      repository: solairen/docker_tag
  #      ref: main
  #      token: ${{ secrets.token }}
  #      path: .github/actions/solairen/docker_tag 
  #  - name: push docker image to Docker Hub
  #    uses: ./.github/actions/solairen/docker_tag
  #    with:
  #      username: ${{ secrets.DOCKER_USERNAME }}
  #      password: ${{ secrets.DOCKER_PASSWORD }}
  #      repository: "moleszek/terraform"
  #      tag_latest: "false"
  #      push: "true"
  #  - name: update Docker README
  #    uses: peter-evans/dockerhub-description@v2.1.0
  #    env:
  #      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #      DOCKERHUB_REPOSITORY: moleszek/terraform
  #      README_FILEPATH: README.md