name: Test docker image
on:
  push:
    branches:
      - '*'
jobs:
  Test_Image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: get docker_tag repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/docker_tag
        ref: master
        token: ${{ secrets.token }}
        path: .github/actions/docker_tag
    - name: test docker image
      uses: ./.github/actions/docker_tag
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_latest: false
        push: false
        github: true
        token: ${{ secrets.token }}
        owner: ${{ github.repository_owner }}